In [30]:
import pandas as pd
data = pd.read_csv('prostate.txt')
data

,lcavol,lweight,age,lbph,svi,lcp,gleason,pgg45,lpsa,train
0,-0.579818,2.769459,50,-1.386294,0,-1.386294,6,0,-0.430783,True
1,-0.994252,3.319626,58,-1.386294,0,-1.386294,6,0,-0.162519,True
2,-0.510826,2.691243,74,-1.386294,0,-1.386294,7,20,-0.162519,True
3,-1.203973,3.282789,58,-1.386294,0,-1.386294,6,0,-0.162519,True
4,0.751416,3.432373,62,-1.386294,0,-1.386294,6,0,0.371564,True
...,...,...,...,...,...,...,...,...,...,...
92,2.830268,3.876396,68,-1.386294,1,1.321756,7,60,4.385147,True
93,3.821004,3.896909,44,-1.386294,1,2.169054,7,40,4.684443,True
94,2.907447,3.396185,52,-1.386294,1,2.463853,7,10,5.143124,False
95,2.882564,3.773910,68,1.558145,1,1.558145,7,80,5.477509,True
96,3.471966,3.974998,68,0.438255,1,2.904165,7,20,5.582932,False

In [31]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   lcavol   97 non-null     float64
 1   lweight  97 non-null     float64
 2   age      97 non-null     int64
 3   lbph     97 non-null     float64
 4   svi      97 non-null     int64
 5   lcp      97 non-null     float64
 6   gleason  97 non-null     int64
 7   pgg45    97 non-null     int64
 8   lpsa     97 non-null     float64
 9   train    97 non-null     bool
dtypes: bool(1), float64(5), int64(4)
memory usage: 7.0 KB

,lcavol,lweight,age,lbph,svi,lcp,gleason,pgg45,lpsa
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,1.350010,3.628943,63.865979,0.100356,0.216495,-0.179366,6.752577,24.381443,2.478387
std,1.178625,0.428411,7.445117,1.450807,0.413995,1.398250,0.722134,28.204035,1.154329
min,-1.347074,2.374906,41.000000,-1.386294,0.000000,-1.386294,6.000000,0.000000,-0.430783
25%,0.512824,3.375880,60.000000,-1.386294,0.000000,-1.386294,6.000000,0.000000,1.731656
50%,1.446919,3.623007,65.000000,0.300105,0.000000,-0.798508,7.000000,15.000000,2.591516
75%,2.127041,3.876396,68.000000,1.558145,0.000000,1.178655,7.000000,40.000000,3.056357
max,3.821004,4.780383,79.000000,2.326302,1.000000,2.904165,9.000000,100.000000,5.582932

In [32]:
import pandas as pd
data = pd.read_csv('prostate.txt')
data

,lcavol,lweight,age,lbph,svi,lcp,gleason,pgg45,lpsa,train
0,-0.579818,2.769459,50,-1.386294,0,-1.386294,6,0,-0.430783,True
1,-0.994252,3.319626,58,-1.386294,0,-1.386294,6,0,-0.162519,True
2,-0.510826,2.691243,74,-1.386294,0,-1.386294,7,20,-0.162519,True
3,-1.203973,3.282789,58,-1.386294,0,-1.386294,6,0,-0.162519,True
4,0.751416,3.432373,62,-1.386294,0,-1.386294,6,0,0.371564,True
...,...,...,...,...,...,...,...,...,...,...
92,2.830268,3.876396,68,-1.386294,1,1.321756,7,60,4.385147,True
93,3.821004,3.896909,44,-1.386294,1,2.169054,7,40,4.684443,True
94,2.907447,3.396185,52,-1.386294,1,2.463853,7,10,5.143124,False
95,2.882564,3.773910,68,1.558145,1,1.558145,7,80,5.477509,True
96,3.471966,3.974998,68,0.438255,1,2.904165,7,20,5.582932,False

In [33]:
# Avval mavjud ustunlarni aniqlaymiz
cols_to_drop = [col for col in ['id', 'lpsa', 'train'] if col in data.columns]

# Ustunlarni tushiramiz
X = data.drop(cols_to_drop, axis='columns')

# Agar 'lpsa' mavjud boâ€˜lsa, uni y deb ajratamiz
if 'lpsa' in data.columns:
    y = data['lpsa']
else:
    raise ValueError("'lpsa' ustuni DataFrame ichida topilmadi!")

# Train/Test ga ajratamiz
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=55)

# Natijani chiqaramiz
print(X_train.shape, X_test.shape)

(77, 8) (20, 8)

In [34]:
print(data.columns)

Index(['lcavol', 'lweight', 'age', 'lbph', 'svi', 'lcp', 'gleason', 'pgg45',
       'lpsa', 'train'],
      dtype='object')

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   lcavol   97 non-null     float64
 1   lweight  97 non-null     float64
 2   age      97 non-null     int64
 3   lbph     97 non-null     float64
 4   svi      97 non-null     int64
 5   lcp      97 non-null     float64
 6   gleason  97 non-null     int64
 7   pgg45    97 non-null     int64
 8   lpsa     97 non-null     float64
 9   train    97 non-null     bool
dtypes: bool(1), float64(5), int64(4)
memory usage: 7.0 KB

0 - > row
1 - > collumns
 lavel ground truth

In [36]:

cols_to_drop = [col for col in ['id', 'lpsa', 'train'] if col in data.columns]
X = data.drop(cols_to_drop, axis='columns')

if 'lpsa' in data.columns:
    y = data['lpsa']
else:
    raise KeyError("'lpsa' ustuni topilmadi!")
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=55)
print(X_train.shape, X_test.shape)

(77, 8) (20, 8)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(X_train.shape, X_test.shape)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

(67, 8) (30, 8)
Mean Squared Error: 0.4612959596185864
Mean Absolute Error: 0.530383981112604
R2 Score: 0.6039185108581981

In [38]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train, y_train)


y_pred = ridge_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Squared Error: 0.4451186228892906
Mean Absolute Error: 0.49290134977139155
R2 Score: 0.6178088202972527

In [39]:
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train, y_train)


y_pred = lasso_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Squared Error: 0.5404574731660402
Mean Absolute Error: 0.5451558403532795
R2 Score: 0.5359482424983382

### HYPERPARAMTER tuning
Ridge, alpha ,1 ,10, 100

Natijalar:

BAse model (Simple Linnear Regressions): 0.6039185108581981
Ridge(alpha=15) : 0.6178088202972527
Lasso(alpha=0.01) :0.5359482424983382

### Data processing - normalitions

x_scaled = (x-x_min)/(x_max-x-min)

In [40]:
import pandas as pd
data = pd.read_csv('prostate.txt')
data 
cols_to_drop = [col for col in ['id', 'lpsa', 'train'] if col in data.columns]
X = data.drop(cols_to_drop, axis='columns')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [41]:
from sklearn.linear_model import Ridge,Lasso, LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Ma'lumotni o'qish
data = pd.read_csv('prostate.txt')

# Target ustunni ajratish
y = data['lpsa']

# ID va train ustunlarini olib tashlash
cols_to_drop = [col for col in ['id', 'lpsa', 'train'] if col in data.columns]
X = data.drop(cols_to_drop, axis='columns')

# Train-test bo'lish
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Skalirlash
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model qurish
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Bashorat va metrikalar
y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Squared Error: 0.46129595961858627
Mean Absolute Error: 0.5303839811126044
R2 Score: 0.6039185108581981

In [43]:
from sklearn.linear_model import Ridge
ridge_model = Ridge()
ridge_model.fit(X_train_scaled, y_train)

# Bashorat va metrikalar
y_pred = ridge_model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Squared Error: 0.4158121965885847
Mean Absolute Error: 0.5015838360115886
R2 Score: 0.6429721297270723

In [44]:
from sklearn.linear_model import Lasso
lasso_model = Lasso(alpha=0.01)
lasso_model.fit(X_train_scaled, y_train)

# Bashorat va metrikalar
y_pred = lasso_model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Squared Error: 0.4416049725137688
Mean Absolute Error: 0.5216348696806314
R2 Score: 0.620825737840192

In [45]:
X_train.head(1)

      lcavol  lweight  age      lbph  svi       lcp  gleason  pgg45
95  2.882564  3.77391   68  1.558145    1  1.558145        7     80

In [46]:
X_train_scaled[0]

array([0.87394984, 0.58159109, 0.69444444, 0.79309437, 1.        ,
       0.68627592, 0.33333333, 0.8       ])

In [47]:
a = (7-6)/(9-6)
a

0.3333333333333333

### Data preprocessing -standardization

x_scaled = (x - mean)/std

In [51]:
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


data = pd.read_csv('prostate.txt')
X = data.drop(['lpsa', 'train'], axis='columns')
y = data['lpsa']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train_scaled, X_test.shape)


scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


# lasso_model = Lasso(alpha=0.01)
# lasso_model.fit(X_train_scaled, y_train)

ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train_scaled, y_train)

# Bashorat va metrikalar
y_pred = ridge_model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

[[-0.12469333 -0.21218779  0.78741288  0.80598507 -0.53229065 -0.42892998
  -1.21976137 -0.84401113]
 [ 0.43355199 -0.15577023 -0.63251199 -1.07345361  1.87867287  1.10500403
   0.55234477  1.52640311]
 [-1.57150246  1.67902815  0.64542039 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.15330463 -1.35325558  0.21944293 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.49207437 -1.46120529 -1.20048193  0.50798465 -0.53229065  0.0311849
   0.55234477 -0.64647661]
 [-1.17555636 -0.88830969 -1.4844669  -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.99053642 -0.94034139 -0.20653453 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.08970442 -1.33227368  0.21944293  0.25162089 -0.53229065  0.31019776
   0.55234477  0.73626503]
 [-2.35325094 -0.14342277 -0.20653453  0.73328103 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.0816687   0.39111627 -0.4905195   0.7706029  -0.53229065 -0.1628944
   0.55234477 -0.05387305]
 [ 1.31744383  0.2508971   0.50342791  0.93157268  1.87867287  1.27602277
   0.55234477  2.31654119]
 [-0.93669894  0.96257842  0.07745045  1.20719758 -0.53229065 -0.42892998
  -1.21976137 -0.84401113]
 [-0.28138661 -1.20046167  0.36143542  0.02249892 -0.53229065  0.18405939
   0.55234477  2.31654119]
 [ 0.31862718 -0.6602361  -0.34852701 -1.07345361  1.87867287  0.36587629
   0.55234477  0.34119599]
 [-2.09528091 -0.97571179 -2.05243685 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.25984812 -0.60665393 -0.4905195   0.28946138 -0.53229065 -0.85417238
   0.55234477 -0.25140757]
 [-0.14804499  2.51577504  1.07139785  1.45465195 -0.53229065 -0.42892998
   0.55234477 -0.64647661]
 [-0.04875385  1.02936992 -0.06454204  1.34912811 -0.53229065 -0.85417238
   0.55234477 -0.64647661]
 [-1.54479725 -0.32945153  0.78741288  0.71776005 -0.53229065 -0.28375198
   0.55234477  0.34119599]
 [-0.12982856  0.36670939  0.64542039 -1.07345361  1.87867287  0.31019776
   0.55234477 -0.05387305]
 [-1.19291396 -1.00260752 -0.20653453 -1.07345361 -0.53229065 -0.42892998
  -1.21976137 -0.84401113]
 [-0.58264331 -0.27657821 -0.91649696  0.91708376 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.08467006  1.39005438  0.21944293  1.31571013 -0.53229065 -0.85417238
   0.55234477 -0.25140757]
 [-1.53174661  0.45808104  0.36143542  1.10746808 -0.53229065 -0.85417238
   0.55234477 -0.05387305]
 [-1.02596382  0.36670939  0.78741288  0.99972488 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 1.22794811  0.36179696 -0.20653453 -1.07345361 -0.53229065  0.41757427
   0.55234477  1.13133407]
 [ 0.07151828 -1.21033154  0.50342791  0.07490581 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.66176242  1.03302218  0.50342791  1.0734133  -0.53229065  1.19555504
   0.55234477  0.73626503]
 [ 0.09766641 -1.49462691  0.36143542 -1.07345361 -0.53229065 -0.85417238
   0.55234477 -0.64647661]
 [-0.84984141  0.0112164   0.64542039  0.95965723 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-2.22906073 -0.85427822 -0.91649696 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.80187318 -0.02938147  0.21944293 -1.07345361 -0.53229065  0.41757427
  -1.21976137 -0.84401113]
 [ 1.12512374  0.9512526   0.50342791  0.80598507  1.87867287  1.4745679
   0.55234477  0.53873051]
 [-1.85810303 -0.27657821 -2.47841431 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.56096541  1.73583052  1.07139785  1.31571013 -0.53229065  0.51105429
   0.55234477  1.52640311]
 [-0.54444321 -0.42507853 -0.06454204  0.28946138 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 1.11413813 -0.18066993  0.64542039 -1.07345361  1.87867287  2.01819027
   0.55234477  1.92147215]
 [ 0.05085419 -0.01189205  1.21339034 -0.52428097 -0.53229065  1.34842953
   2.32445091 -0.25140757]
 [ 1.68218917 -0.32277486 -0.06454204 -1.07345361  1.87867287  1.83246275
   0.55234477  1.52640311]
 [-0.33841923 -1.79431217 -2.47841431 -1.07345361 -0.53229065  0.51105429
   0.55234477 -0.68598352]
 [ 1.82895769  0.70340777  0.50342791  0.16897978  1.87867287  2.24981991
   0.55234477 -0.05387305]
 [ 1.55265469 -0.32945153 -0.77450447 -1.07345361 -0.53229065 -0.85417238
   0.55234477 -0.64647661]
 [ 0.35325549  0.52768318 -0.4905195  -1.07345361 -0.53229065  0.73544017
   0.55234477 -0.60696971]
 [-0.23656507  0.74527482  0.50342791 -1.07345361 -0.53229065 -0.85417238
   0.55234477  1.13133407]
 [ 0.57135896  0.48618069  0.50342791  1.08495516 -0.53229065  1.10500403
   0.55234477  1.92147215]
 [ 1.18317796  0.7494199   2.06534526  1.15037698  1.87867287  2.07082904
   4.09655705  3.10667928]
 [ 0.72363546  0.87424468  1.07139785  1.44189838 -0.53229065 -0.1628944
   0.55234477 -0.44894209]
 [ 0.54926913  0.12879744 -0.20653453  0.97327675  1.87867287  1.53024643
   0.55234477  0.73626503]
 [ 1.33903925 -0.59910188 -1.76845188 -1.07345361  1.87867287  1.93127021
   0.55234477 -0.44894209]
 [ 1.01811652  1.55804464  1.92335277  1.45465195 -0.53229065 -0.85417238
   0.55234477 -0.44894209]
 [ 0.06742464  0.04544364  0.50342791 -1.07345361 -0.53229065 -0.85417238
   0.55234477 -0.44894209]
 [-0.7135351   1.16073411  0.78741288  0.16897978 -0.53229065 -0.85417238
   0.55234477 -0.05387305]
 [ 0.33082916 -0.36993689 -3.04638426 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 0.17169199  0.1068704  -0.63251199  1.02518405 -0.53229065  0.73544017
   0.55234477  0.34119599]
 [-0.78173975  0.23013122 -2.19442934  0.83961924 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.07736692 -1.40658347  0.92940537  0.73328103 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 1.01399043  0.03409307 -0.4905195   0.78852376  1.87867287 -0.85417238
   0.55234477 -0.25140757]
 [-0.26317928  0.42484844 -0.4905195   0.75219763 -0.53229065 -0.85417238
   0.55234477  0.73626503]
 [ 0.58162951  0.57291895  0.21944293  1.23804906  1.87867287  1.67542443
   0.55234477  1.52640311]
 [ 1.6332786   0.98879005  0.50342791 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.78721517 -2.89729794 -0.06454204 -1.07345361 -0.53229065 -0.85417238
   0.55234477 -0.25140757]
 [ 0.90702027 -0.64479446  0.07745045 -1.07345361 -0.53229065  1.32033031
  -1.21976137 -0.84401113]
 [-2.04705456 -0.77138349 -0.91649696 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.73913728 -0.06477437 -0.06454204  0.88714692 -0.53229065  0.18405939
   0.55234477  1.92147215]
 [ 0.60292066 -0.3631387  -0.63251199  0.87479368 -0.53229065  1.12404366
   0.55234477 -0.05387305]
 [-1.62751228 -2.1854411   1.35538283 -1.07345361 -0.53229065 -0.85417238
   0.55234477 -0.05387305]
 [ 0.36206624 -0.47445937 -0.20653453  0.16897978 -0.53229065  1.00147575
   0.55234477  1.52640311]
 [ 1.25238127  2.37551087  0.07745045 -1.07345361  1.87867287  1.93127021
   0.55234477  1.52640311]
 [ 1.41868958  0.42005978  0.64542039 -1.07345361  1.87867287  1.53024643
   0.55234477 -0.05387305]
 [ 0.57250616  0.15590919 -0.91649696  0.9866292  -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [ 1.0835086   0.50933189  1.78136029 -0.48874489  1.87867287  0.55362326
   0.55234477  0.34119599]
 [-0.18841743 -0.54693966 -0.77450447 -1.07345361 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.78721517  1.93996304  1.21339034  1.45465195 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]
 [-0.17746648 -0.72307605  1.78136029  1.06167243 -0.53229065 -0.85417238
   0.55234477  0.14366147]
 [-0.13758883 -0.4959611  -1.05848944 -1.07345361 -0.53229065 -0.1628944
   0.55234477 -0.64647661]
 [ 1.27205893  0.48152254  0.50342791 -1.07345361  1.87867287  1.10500403
   0.55234477  1.52640311]
 [ 0.25655456  1.28811301 -0.06454204  1.28228238 -0.53229065 -0.85417238
  -1.21976137 -0.84401113]] (20, 8)

Mean Squared Error: 0.35372260282112006
Mean Absolute Error: 0.43045480521343105
R2 Score: 0.7528139307371668

1. Linnear Regression model type (turi)
 - linnear regression 
 - Lasso
 - Ridge

2. Hyperparamater tunning
 - Ridge alpha (10,1) vs hz .. 
 - Lasso alpha (0.01) . ..

3. Data preprocessing
 - Minmaxscaler c scale = (x-x_min)/(x_max-x_min)
 - Standart scaler x_scaled = (x-mean)/std

4. Data splitting:
 - Nechchi % ini testga berish
 - Qanday random value ishlatish
 - 0.2215489754484546848

In [49]:
data

,lcavol,lweight,age,lbph,svi,lcp,gleason,pgg45,lpsa,train
0,-0.579818,2.769459,50,-1.386294,0,-1.386294,6,0,-0.430783,True
1,-0.994252,3.319626,58,-1.386294,0,-1.386294,6,0,-0.162519,True
2,-0.510826,2.691243,74,-1.386294,0,-1.386294,7,20,-0.162519,True
3,-1.203973,3.282789,58,-1.386294,0,-1.386294,6,0,-0.162519,True
4,0.751416,3.432373,62,-1.386294,0,-1.386294,6,0,0.371564,True
...,...,...,...,...,...,...,...,...,...,...
92,2.830268,3.876396,68,-1.386294,1,1.321756,7,60,4.385147,True
93,3.821004,3.896909,44,-1.386294,1,2.169054,7,40,4.684443,True
94,2.907447,3.396185,52,-1.386294,1,2.463853,7,10,5.143124,False
95,2.882564,3.773910,68,1.558145,1,1.558145,7,80,5.477509,True
96,3.471966,3.974998,68,0.438255,1,2.904165,7,20,5.582932,False